### ISSUE TITLE
Curve EQ Balancing silenting fails in GlyphsApp

### ISSUE THREAD

**Issue by arrowtype** [jenskutilek/Curve-Equalizer#12]
Initially, the [balance handles](https://github.com/jenskutilek/Glyphs-Scripts/blob/003fdbdc2cb554517c199ca664426f6654c29144/Outlines/Curve%20EQ%20Balance%20Handles.py) script worked for me in GlyphsApp, but it is now silently failing. I click the button with handles selected, and it doesn’t do anything. I don’t see any errors logged to the "Floating Macro Console," but I’m not 100% sure that is even where I should look for errors in Glyphs (please let me know if not).

This is a bummer, because I really love how the balance handles script works! If I can help by giving more information, please let me know!

Glyphs version: `3.0.4 (3103)`
Modules installed: Python, FontTools, Vanilla
macOS: `10.15.7 (19H2)`

**Comment by jenskutilek** [comment]
There was a problem in the script in how the selection was read from the glyph, so certain segments would not be processed even though they are selected. I've changed that in the script (and the plugin before it was released) since. Could you try [the latest version of the script](https://github.com/jenskutilek/Glyphs-Scripts/blob/master/Outlines/Curve%20EQ%20Balance%20Handles.py)?

Another scenario where the script doesn't do anything is when the angle between the handles of a segment is less than 45°, because the operation becomes more unprecise the smaller the angle gets.

**Comment by arrowtype** [comment]
Ohh, thanks! Will update when I'm back to my computer. I did try to download the Curve EQ module yesterday, thinking it would have any recent commits, but those are probably cached and reviewed. 🤔

**Comment by arrowtype** [comment]
Good to know about the 45 degree limitation. I hadn't noticed that before! I'll keep an eye on curves like that, as I probably have quite a few near sand-serif terminals...
