### ISSUE TITLE
Analytics.pyc tries to connect to ws.kutilek.de

### ISSUE THREAD

**Issue by typemytype** [jenskutilek/Curve-Equalizer#2]
but ws.kutilek.de doesnt responds...

**Comment by jenskutilek** [comment]
I had some load problems on my webserver, it should be fixed now. That said, I could work around failing connections better, because it may happen when you just are not connected to the internet.

I never found time to look at the analytics data anyway, so while extensions with analytics may have been a good idea, maybe I should just deactivate the whole thing.

**Comment by typemytype** [comment]
This thing should fail silently ;)

thanks

is the source for analytics opensource?

**Comment by jenskutilek** [comment]
It's not open source ... I disabled analytics in CurveEQ.
